export { backIcon } from "./BackIcon";
export { closeIcon } from "./CloseIcon";
export { deleteIcon } from "./DeleteIcon";
export { favorisIcon } from "./FavorisIcon";
export { localisationIcon } from "./LocalisationIcon";
export { menuIcon } from "./MenuIcon";
export { messageIcon } from "./MessageIcon";
export { plusIcon } from "./PlusIcon";
export { sendIcon } from "./SendIcon";
