export const equipments = [
  "Micro-Ondes",
  "Douche Italienne",
  "Frigo",
  "Wifi",
  "Parking",
  "Seche Cheveux",
  "Machine a laver",
  "Cuisine equipee",
  "Television",
  "Cheminée Separee",
  "Climatisation",
  "Frigo Americain",
  "Clic-clac",
  "Four",
  "Rangements",
  "Lit",
  "Isolable",
  "SDB",
  "Toilettes seches",
  "Cintres",
  "Baie vitree",
  "Hotte",
  "Baignoire",
  "Vue Parc",
];

export const categories = [
  "Parc",
  "Night Life",
  "Culture",
  "Nature",
  "Touristique",
  "Parc",
  "Night Life",
  "Culture",
  "Nature",
  "Touristique",
  "Parc",
  "Night Life",
  "Culture",
  "Nature",
  "Touristique",
  "Vue sur mer",
  "Pour les couples",
  "Famille",
  "Foret",
];
